global:
  resolve_timeout: 1m

route:
  receiver: 'webhook'
  group_wait: 1s
  group_interval: 1m
  repeat_interval: 30s

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://web:8000/test/alerts/webhook/'