version: '3'

services:
  web:
    build: .
    command: /app/run.sh
    volumes:
      - ./baliqchi:/app/baliqchi
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=baliqchi.settings

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  prometheus_data:
