# Generated by Django 5.0.6 on 2024-05-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phishing',
            fields=[
                ('baseattack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseattack')),
                ('message', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('core.baseattack',),
        ),
    ]
