# Generated by Django 5.0.6 on 2024-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishing',
            name='html',
            field=models.FileField(blank=True, upload_to='staticfiles/phishing_pages/'),
        ),
    ]
