# Generated by Django 5.0.6 on 2024-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0004_alter_phishing_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishing',
            name='html',
            field=models.FileField(blank=True, upload_to='baliqchi/attacks/phishing/templates/phishing/bfb4c0af-af45-4d0b-a059-c2d526ff06f6/'),
        ),
    ]
