# Generated by Django 5.0.6 on 2024-05-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_baseattack_sent_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targets",
                to="core.target",
                verbose_name="Targets",
            ),
        ),
    ]
