# Generated by Django 5.0.6 on 2024-05-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_incident_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="core.target",
                verbose_name="Target",
            ),
        ),
    ]
