# Generated by Django 5.0.6 on 2024-05-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_incident_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseattack",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("firing", "Firing"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("labels", models.JSONField()),
                ("annotations", models.JSONField()),
                ("starts_at", models.DateTimeField()),
                ("generator_url", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=255, unique=True)),
                ("timestamp", models.BigIntegerField(default=1716119933394)),
                (
                    "incident",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.incident",
                    ),
                ),
            ],
        ),
    ]
