# Generated by Django 5.0.6 on 2024-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_alert_fingerprint_alter_alert_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="timestamp",
            field=models.BigIntegerField(default=1716130117678),
        ),
    ]
